### PR TITLE
It's possible to save the filters with the same name for Messages

### LINKED ISSUE #2366: It's possible to save the filters with the same name for Messages
**Describe the bug**
It's possible to save the filters with the same name for Messages

**Set up**
https://www.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Navigate to Topics
2. Turn to Messages tab for any Topic
3. Press "+ Add Filters"
4. Turn to Saved Filters
5. Check the existing Filters
6. Add the filter with the same name

**Expected behavior**
Should not be possible to submit the Filter with the same name

**Screenshots**

https://user-images.githubusercontent.com/104780608/182073770-3e266ef0-e268-44cb-8d08-c12c9aded862.mov

**Additional context**

### PR DESCRIPTION
**Pull request by NeiruBugz**
- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)
Resolves #2366
- add validation for existing filter
- add an error-type alert for trying to create a filter with the same name
- update typings for form callback
**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary)
- [ ] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/AddFilter.tsx [hunk 1]
```diff
@@ -43,6 +44,19 @@ const AddFilter: React.FC<FilterModalProps> = ({
...
     async (values: AddMessageFilters) => {
+      const isFilterExists = filters.some(
+        (filter) => filter.name === values.name
+      );
+
+      if (isFilterExists) {
+        showAlert('error', {
+          id: '',
+          title: 'Validation Error',
+          message: 'Filter with the current name already exists',
```
Comment (workshur) [inline kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/AddFilter.tsx:55]: i would suggest to use `same` instead of current here 
```suggestion
          message: 'Filter with the same name already exists',
```

**Review by workshur — APPROVED** [review]

**Comment by workshur** [comment]
@Haarolean please check how it works

File: kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/AddFilter.tsx (hunk 1 above)
Comment (NeiruBugz) [reply kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/AddFilter.tsx]: Updated

**Review by Mgrdich — APPROVED** [review]
