### PR TITLE
FE: Broker: Config: Implement search by the Value

### LINKED ISSUE #3163: Broker: Config: Implement search by the Value
**Actual behavior**

It is not possible to search by the config Value and only works for the Key now.

**Expected behavior**
Search by the config Value can be useful for maintenance and troubleshooting.

**Set up**

[f4e6afe](https://github.com/provectus/kafka-ui/commit/f4e6afe)

**Steps to Reproduce**

1. Login to Kafka UI
2. Navigate to Borkers
3. Select broker and switch to Configs tab.

**Screenshots**

**Additional context**

Discussed with @Haarolean to be created as a separate issue from #2651

### PR DESCRIPTION
**Pull request by malavmevada**
- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)
In BrokerConfigTab, I have added search by value functionality and basically changed the method getData by filter out brokerconfig name or value.
Closes #3163

**Is there anything you'd like reviewers to focus on?**
BrokersConfigTab.java and Configs.tsx are changed. Please refer those.

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [x] No need to
- [x] Manually (please, describe, if necessary)
- [x] Unit checks
- [x] Integration checks
- [x] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by David-DB88 — COMMENTED** [review]
I think we should remove the case sensitivity of the search text

**Comment by malavmevada** [comment]
> I think the search text should be case insensitive. keyword.toLocaleLowerCase()

Yeah. You are right.

File: kafka-ui-react-app/src/components/Brokers/Broker/Configs/Configs.tsx [hunk 1]
```diff
@@ -34,14 +34,13 @@ const Configs: React.FC = () => {
...
   const getData = () => {
     return data
-      .filter(
-        (item) =>
-          item.name.toLocaleLowerCase().indexOf(keyword.toLocaleLowerCase()) >
-          -1
-      )
+      .filter((item) => {
+        const nameMatch = item.name.toLocaleLowerCase().includes(keyword);
+        const valueMatch = item.value && item.value.includes(keyword);
```
Comment (Mgrdich) [inline kafka-ui-react-app/src/components/Brokers/Broker/Configs/Configs.tsx:39]: you can actually check the `nameMatch` before doing value check , so it wouldn't do more work if it does not have to.

Comment (malavmevada) [reply kafka-ui-react-app/src/components/Brokers/Broker/Configs/Configs.tsx:39]: Actually i don't get it what you are saying. Do you mean that if nameMatch found then i don't need to check for valueMatch ?

Comment (shailshouryya) [reply kafka-ui-react-app/src/components/Brokers/Broker/Configs/Configs.tsx:39]: > Actually i don't get it what you are saying. Do you mean that if nameMatch found then i don't need to check for valueMatch ?

Yep, I think this is correct, and I think the suggestion is to do something like
```
      .filter((item) => {
        const nameMatch = item.name.toLocaleLowerCase().includes(keyword);
        return nameMatch ? nameMatch : item.value && item.value.includes(keyword); // try to match the keyword on any of the item.value elements when nameMatch fails but item.value exists
      })
```

or more explicitly:
```
      .filter((item) => {
        const nameMatch = item.name.toLocaleLowerCase().includes(keyword);
        if (nameMatch === true) return nameMatch;
        const valueMatch = item.value && item.value.includes(keyword);
        return valueMatch;
      })
```
instead of (the current implementation):
```
      .filter((item) => {
        const nameMatch = item.name.toLocaleLowerCase().includes(keyword);
        const valueMatch = item.value && item.value.includes(keyword);
        return nameMatch || valueMatch;
      })
```

so we don't need to go through the entire `item.value` array in case we find a `nameMatch` (and `item.value` exists).

**Review by Mgrdich — APPROVED** [review]

File: kafka-ui-react-app/src/components/Brokers/Broker/Configs/Configs.tsx [hunk 2]
```diff
@@ -34,14 +34,12 @@ const Configs: React.FC = () => {
...
   const getData = () => {
     return data
-      .filter(
-        (item) =>
-          item.name.toLocaleLowerCase().indexOf(keyword.toLocaleLowerCase()) >
-          -1
-      )
+      .filter((item) => {
+        const nameMatch = item.name.toLocaleLowerCase().includes(keyword);
+        return nameMatch ? true : item.value && item.value.includes(keyword); // try to match the keyword on any of the item.value elements when nameMatch fails but item.value exists
```
Comment (Haarolean) [inline kafka-ui-react-app/src/components/Brokers/Broker/Configs/Configs.tsx:39]: @malavmevada shouldn't we cast item value to lower case as well?

**Review by Haarolean — CHANGES_REQUESTED** [review]

File: kafka-ui-react-app/src/components/Brokers/Broker/Configs/Configs.tsx (hunk 2 above)
Comment (malavmevada) [reply kafka-ui-react-app/src/components/Brokers/Broker/Configs/Configs.tsx:39]: @Haarolean Actually, we shouldn't convert the 'item' values to lowercase because if you observe, all the values under the 'name' key are in lowercase strings. However, for the 'item' key, we can have values in uppercase, lowercase, null, and numbers. Due to this diversity, I haven't changed the 'item' values to lowercase.

**Review by malavmevada — COMMENTED** [review]
Actually, we shouldn't convert the 'item' values to lowercase because if you observe, all the values under the 'name' key are in lowercase strings. However, for the 'item' key, we can have values in uppercase, lowercase, null, and numbers. Due to this diversity, I haven't changed the 'item' values to lowercase.

File: kafka-ui-react-app/src/components/Brokers/Broker/Configs/Configs.tsx (hunk 2 above)
Comment (Haarolean) [reply kafka-ui-react-app/src/components/Brokers/Broker/Configs/Configs.tsx:39]: @malavmevada sorry for the delay. Isn't this the point? Let's say I have some setting but in order to find it but its value I have to remember the exact case-sensitive value?

Comment (malavmevada) [reply kafka-ui-react-app/src/components/Brokers/Broker/Configs/Configs.tsx:39]: Yes you are absolutely right. Sorry for the mistake. I got your point and I have tested it and yeah it's working fine.

File: kafka-ui-react-app/src/components/Brokers/Broker/Configs/Configs.tsx [hunk 3]
```diff
@@ -34,14 +34,12 @@ const Configs: React.FC = () => {
...
   const getData = () => {
     return data
-      .filter(
-        (item) =>
-          item.name.toLocaleLowerCase().indexOf(keyword.toLocaleLowerCase()) >
-          -1
-      )
+      .filter((item) => {
+        const nameMatch = item.name.toLocaleLowerCase().includes(keyword);
+        return nameMatch ? true : item.value && item.value.toLocaleLowerCase().includes(keyword); // try to match the keyword on any of the item.value elements when nameMatch fails but item.value exists
```
Comment (Haarolean) [inline kafka-ui-react-app/src/components/Brokers/Broker/Configs/Configs.tsx:39]: please cast the keyword to lowercase as well, otherwise it's not a case-insensitive search :)

Comment (malavmevada) [reply kafka-ui-react-app/src/components/Brokers/Broker/Configs/Configs.tsx]: Yes @Haarolean. I have updated it.

**Review by Haarolean — APPROVED** [review]

**Comment by Haarolean** [comment]
@malavmevada there are some linter issues which prevent the build from succeeding, otherwise looks good

**Comment by malavmevada** [comment]
> @malavmevada there are some linter issues which prevent the build from succeeding, otherwise looks good

**Comment by malavmevada** [comment]
@Haarolean Actually I'm very new to this and because of that I made many small mistakes btw thank you. Do i need to change anything now ?

**Comment by malavmevada** [comment]
@Haarolean There are some issues regarding formatting the code in Linter. What should I do now ?

**Comment by Haarolean** [comment]
> @Haarolean There are some issues regarding formatting the code in Linter. What should I do now ?

I guess fixing line breaks would be nice :)
https://github.com/provectus/kafka-ui/pull/3804/files

image

**Comment by malavmevada** [comment]
@Haarolean Linter issue is resolved.

**Comment by Haarolean** [comment]
@malavmevada thank you, will be merged soon
