### PR TITLE
Seek type field became empty with refreshing the page

### LINKED ISSUE #2857: Seek type field became empty with refreshing the page
**Describe the bug**
Seek type field became empty with refreshing the Topic/Messages

**Set up**
https://www.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Navigate to Topic/Messages tab
2. Make sure Seek Type value is "Offset" by default
3. Refresh the page

**Expected behavior**
The default "Offset" value should stay for Seek Type

**Screenshots**

https://user-images.githubusercontent.com/104780608/199174719-8ddb7f18-3526-4335-b70c-63c2739d92a5.mov

**Additional context**

### PR DESCRIPTION
**Pull request by winnie-chiu**
- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)
Set the seek type field default value to offset after refreshing the page.
Closes #2857 

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary)
- [ ] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/Filters.tsx [hunk 1]
```diff
@@ -109,7 +109,11 @@ const Filters: React.FC<FiltersProps> = ({
   );
 
   const [currentSeekType, setCurrentSeekType] = React.useState<SeekType>(
-    (searchParams.get('seekType') as SeekType) || SeekType.OFFSET
+    SeekTypeOptions.map(({ value }) => value).includes(
```
Comment (Mgrdich) [inline kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/Filters.tsx:112]: i think we can use find here instead of iterating over the array twice , 
[MDN doc for find](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find)

**Review by Mgrdich — APPROVED** [review]

**Comment by Haarolean** [comment]
@armenuikafka it's from a fork 🙃

**Review by armenuikafka — APPROVED** [review]

**Comment by Haarolean** [comment]
@winnie-chiu @armenuikafka thank you
