### PR TITLE
Consumers: Topic list: Implement sorting

### LINKED ISSUE #3168: Consumers: Topic list: Implement sorting
**Describe the bug**

No sorting on visible values is applied, so the list looks as in random order (Partition would be the logical suggestion). Of the "Partition", "Consumer ID", "Host", "Messages behind", "Current offset", "End offset" columns

**Expected behavior**

At least the first 4 columns can be valid candidates for sorting via click on the column headers in a nested table.

**Set up**

[f4e6afe](https://github.com/provectus/kafka-ui/commit/f4e6afe)

**Steps to Reproduce**

1. Log in to Kafka UI and navigate to the Consumers page.
2. Open consumer group details of the topic with the large number of partitions.

**Screenshots**

image

**Additional context**

@Haarolean required to open this as a separate issue from the #2651

### PR DESCRIPTION
**Pull request by NeiruBugz**
- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)
Resolves #3168
implement sorting for consumers topics
**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary)
- [ ] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: kafka-ui-react-app/src/components/ConsumerGroups/Details/TopicContents/TopicContents.tsx [hunk 1]
```diff
@@ -9,24 +9,146 @@ interface Props {
...
+const TABLE_HEADERS_MAP: Headers[] = [
+  { title: 'Partition', orderBy: 'partition' },
+  { title: 'Consumer ID', orderBy: 'consumerId' },
+  { title: 'Host', orderBy: 'host' },
+  { title: 'Messages Behind', orderBy: 'messagesBehind' },
+  { title: 'Current Offset', orderBy: 'currentOffset' },
+  { title: 'End offset', orderBy: 'endOffset' },
+];
+
+const ipV4ToNum = (ip: string | undefined): number => {
```
Comment (Mgrdich) [inline kafka-ui-react-app/src/components/ConsumerGroups/Details/TopicContents/TopicContents.tsx:27]: * `(ip?: string)`  undefined can be written like this

* one more thing here the typescript can automatically infer your return type you don't need to specify the return type.

Comment (NeiruBugz) [reply kafka-ui-react-app/src/components/ConsumerGroups/Details/TopicContents/TopicContents.tsx]: Updated

**Review by Mgrdich — APPROVED** [review]
