### PR TITLE
Issues/1265

### LINKED ISSUE #1265: Consumer, connect labels status colors
1. Consumer and connect statuses are always yellow now, let's color them depending on the status
1.1 STABLE - green
1.2 DEAD - red
1.3 EMPTY - white
1.4 COMPLETING_REBALANCE, PREPARING_REBALANCE - yellow
1.5. UNKNOWN - yellow
2. Connect statuses
2.1  RUNNING. - green
2.2 FAILED - red
2.3 PAUSED - yellow
2.4 UNASSIGNED - yellow
3. In sync replicas dot should display real status
4. Check other metric widgets with status

### PR DESCRIPTION
**Pull request by NelyDavtyan**
- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing applications:)

**What changes did you make?** (Give an overview)
Fixes #1265
**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "X" next to an item)

- [x] No need to
- [x] Manually(please, describe, when necessary)
- [x] Unit checks
- [x] Integration checks
- [x] Covered by existing automation

**Checklist** (put an "X" next to an item, otherwise PR will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings(e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

### CODE REVIEW

File: kafka-ui-react-app/src/components/Brokers/Brokers.tsx [hunk 1]
```diff
@@ -59,7 +59,16 @@ const Brokers: React.FC = () => {
           <Metrics.Indicator label="Version">{version}</Metrics.Indicator>
         </Metrics.Section>
         <Metrics.Section title="Partitions">
-          <Metrics.Indicator label="Online" isAlert>
+          <Metrics.Indicator
+            label="Online"
+            isAlert
+            alertType={
+              onlinePartitionCount ===
+              (onlinePartitionCount || 0) + (offlinePartitionCount || 0)
```
Comment (workshur) [inline kafka-ui-react-app/src/components/Brokers/Brokers.tsx:67]:
```suggestion
    {offlinePartitionCount && offlinePartitionCount > 0 ? 'error' : 'success'}
```

File: kafka-ui-react-app/src/components/Connect/Details/Overview/Overview.tsx [hunk 2]
```diff
@@ -33,11 +33,11 @@ const Overview: React.FC<OverviewProps> = ({
...
           <TagStyled color="yellow">{connector.status.state}</TagStyled>
         </Metrics.Indicator>
-        <Metrics.Indicator label="Tasks running">
+        <Metrics.Indicator label="Tasks Running">
           {runningTasksCount}
         </Metrics.Indicator>
-        <Metrics.Indicator label="Tasks failed" isAlert>
-          {failedTasksCount}
+        <Metrics.Indicator label="Tasks Failed" isAlert>
+          f{failedTasksCount}
```
Comment (workshur) [inline kafka-ui-react-app/src/components/Connect/Details/Overview/Overview.tsx]: redundand `f` letter
```suggestion
          {failedTasksCount}
```

**Review by workshur — APPROVED** [review]
LGTM

File: kafka-ui-react-app/src/components/ConsumerGroups/List/__test__/ListItem.spec.tsx [hunk 3]
```diff
@@ -1,9 +1,11 @@
 import React from 'react';
-import { mount } from 'enzyme';
+import { mount, render } from 'enzyme';
 import ListItem from 'components/ConsumerGroups/List/ListItem';
 import { ThemeProvider } from 'styled-components';
 import theme from 'theme/theme';
 import { StaticRouter } from 'react-router';
+import { ConsumerGroupState } from 'generated-sources';
+import { screen } from '@testing-library/react';
```
Comment (workshur) [inline kafka-ui-react-app/src/components/ConsumerGroups/List/__test__/ListItem.spec.tsx:8]: @NelyDavtyan pls fix all this warnings
