### PR TITLE
[FE] Messages filtering by offset & timestamp doesn't work

### LINKED ISSUE #3568: Messages filtering by offset & timestamp doesn't work
when we use all partitions, the filter does not work.
when we use certain partitions, the filter works

### PR DESCRIPTION
**Pull request by NeiruBugz**
- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)
Resolves #3568 
Moved seekType condition to its own variable for easier dive into filtering logic
Update the condition for adding seekTo property to search query
**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary)
- [ ] Unit checks
- [ ] Integration checks
- [x] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/Filters.tsx [hunk 1]
```diff
@@ -231,9 +231,13 @@ const Filters: React.FC<FiltersProps> = ({
         props.seekType = SeekType.TIMESTAMP;
       }
 
+      const isSeekTypeWithSeekTo =
+        props.seekType === SeekType.TIMESTAMP ||
+        props.seekType === SeekType.OFFSET;
```
Comment (NeiruBugz) [inline kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/Filters.tsx:236]: Correct me if I'm wrong: seekTo exists in the query only with this seek types?

Comment (workshur) [reply kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/Filters.tsx:236]: @Haarolean @iliax

Comment (Haarolean) [reply kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/Filters.tsx:236]: @NeiruBugz yep that's right

File: kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/Filters.tsx [hunk 2]
```diff
@@ -231,9 +231,13 @@ const Filters: React.FC<FiltersProps> = ({
...
+
       if (
         selectedPartitions.length !== partitions.length ||
-        currentSeekType === SeekType.TIMESTAMP
+        isSeekTypeWithSeekTo
```
Comment (Mgrdich) [inline kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/Filters.tsx:240]: doesn't this give us the issue where we had all the partitions selected, now the first part of the `if` condition is `false` but the second one because we are using `OR` will be true hence we will have that `url` length issue again during `offset` and `timestamp`

Comment (p-eye) [reply kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/Filters.tsx:240]: @Mgrdich 
hi, this is my suggestion https://github.com/provectus/kafka-ui/issues/3525 to solve the `url length isssue`. could you teams review it?

Comment (NeiruBugz) [reply kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/Filters.tsx:240]: Hey @Mgrdich
I've made a short review of the @p-eye solution for not combining offset with partition - it seems this one should work fine, but it probably needs some task on the backend to support this kind of payload and a bit of refactoring on the client side

Comment (Haarolean) [reply kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/Filters.tsx:240]: @Mgrdich the suggested change doesn't work well with pagination. The decision, for now, is to fix search modes considering that we might break the URL length fix.

**Review by Haarolean — APPROVED** [review]
