### PR TITLE
Bugfix/2320 move tasks to a new table

### LINKED ISSUE #2320: Hide KC connectors' stacktraces into a spoiler
Hide the stacktrace into a spoiler:
image
like this:
image

### LINKED ISSUE #2321: Do not display "null" as a stacktrace in KC
Make it an empty space
image

### PR DESCRIPTION
**Pull request by KriKiparoidze**
- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

- Moved tasks to new table and wrote tests.
- fixes #2320
- fixes #2321 
**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [ ] Manually (please, describe, if necessary)
- [x] Unit checks
- [x] Integration checks
- [x] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**
Screenshot 2022-08-16 at 16 01 55

### CODE REVIEW

File: kafka-ui-react-app/src/components/Connect/Details/Tasks/Tasks.tsx [hunk 1]
```diff
@@ -1,69 +1,57 @@
...
-          </tr>
-        ))}
-      </tbody>
-    </Table>
+    <Table
+      columns={columns}
+      data={data}
+      emptyMessage="No tasks found"
+      enableSorting
+      getRowCanExpand={() => true}
```
Comment (workshur) [inline kafka-ui-react-app/src/components/Connect/Details/Tasks/Tasks.tsx:52]: let's try to hide expander for rows with empty trace. You can use `getRowCanExpand` to check if row.original.trace.length > 0

File: kafka-ui-react-app/src/components/Connect/Details/Tasks/ActionsCellTasks.tsx [hunk 2]
```diff
@@ -0,0 +1,28 @@
...
+  const restartMutation = useRestartConnectorTask(routerProps);
+
+  const restartTaskHandler = (taskId?: number) => {
+    if (taskId === undefined) return;
+    restartMutation.mutateAsync(taskId);
+  };
+
+  return (
+    <Dropdown>
+      <DropdownItem onClick={() => restartTaskHandler(id?.task)} danger>
```
Comment (workshur) [inline kafka-ui-react-app/src/components/Connect/Details/Tasks/ActionsCellTasks.tsx:21]: let's add confirmation modal. just add `confirm` attr to DropdownItem

**Review by workshur — COMMENTED** [review]
Great job!

File: kafka-ui-react-app/src/components/Connect/Details/Tasks/Tasks.tsx [hunk 3]
```diff
@@ -1,69 +1,57 @@
...
+    () => [
+      { header: 'ID', accessorKey: 'status.id' },
+      { header: 'Worker', accessorKey: 'status.workerId' },
+      { header: 'State', accessorKey: 'status.state', cell: TagCell },
+      {
+        header: 'Trace',
+        accessorKey: 'status.trace',
+        enableSorting: false,
+        cell: ({ getValue }) => {
+          const trace = getValue<Task['status']>() || '';
```
Comment (workshur) [inline kafka-ui-react-app/src/components/Connect/Details/Tasks/Tasks.tsx:31]:
```suggestion
          const trace = getValue<string>() || '';
```

**Review by workshur — APPROVED** [review]
