### PR TITLE
FE: Disable resetting offsets for unassigned CGs

### LINKED ISSUE #3932: Blank page for "Reset offsets" when consumer has no committed offsets
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

Blank page for "Reset offsets" when consumer has no committed offsets

### Expected behavior

Page is rendered

### Your installation details

[80b748b](https://github.com/provectus/kafka-ui/commit/80b748b)

### Steps to reproduce

1. run consumer group that reads from topic, but does not commit offsets
2. stop CG
3. Consumers -> select created CG -> click "..." -> "Reset offsets" 

### Screenshots

https://github.com/provectus/kafka-ui/assets/702205/027eeb5d-d548-4905-bc0c-fad3626efa1b

### Logs

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Haarolean**
- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)
Closes #3932

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary)
- [ ] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: kafka-ui-react-app/src/components/ConsumerGroups/Details/Details.tsx [hunk 1]
```diff
@@ -54,6 +54,10 @@ const Details: React.FC = () => {
     ? filteredPartitionsByTopic
     : Object.keys(partitionsByTopic);
 
+  const hasAssignedTopics = React.useMemo(() => {
```
Comment (Mgrdich) [inline kafka-ui-react-app/src/components/ConsumerGroups/Details/Details.tsx:57]: we don't need the `useMemo` here this is not expensive calculation.
` const hasAssignedTopics = consumerGroup?.data?.topics !== 0`

Comment (Haarolean) [reply kafka-ui-react-app/src/components/ConsumerGroups/Details/Details.tsx:57]: Okay, thank you.
Done

**Review by Mgrdich — APPROVED** [review]
