### PR TITLE
FE: Topics: Remove a success message upon creating a topic

### LINKED ISSUE #3417: Dark mode
**Describe the bug** (Actual behavior)

**Expected behavior**

**Set up**

**Steps to Reproduce**

1. 

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by blacktower88**
Remove success message in case of adding the Topic

- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)
Remove success message in case of adding the Topic
**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary)
- [ ] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: kafka-ui-react-app/src/lib/hooks/api/topics.ts [hunk 1]
```diff
@@ -120,14 +120,15 @@ export function useCreateTopicMutation(clusterName: ClusterName) {
         clusterName,
         topicCreation: formatTopicCreation(data),
       }),
-    {
-      onSuccess: () => {
-        showSuccessAlert({
-          message: `Topic successfully created.`,
-        });
-        client.invalidateQueries(topicKeys.all(clusterName));
```
Comment (Haarolean) [inline kafka-ui-react-app/src/lib/hooks/api/topics.ts:128]: `client.invalidateQueries(topicKeys.all(clusterName));`
this has to be left intact I suppose
Also, please remove the code instead of commenting it

**Review by Haarolean — CHANGES_REQUESTED** [review]
HI, thanks for the contribution. Please take a look at the comments.

**Comment by Haarolean** [comment]
Also, the build

**Comment by blacktower88** [comment]
Sorry, I still have something confused.  Do I need to build the whole project ? As I only fix some part of the frontend.

**Comment by Haarolean** [comment]
> Sorry, I still have something confused. Do I need to build the whole project ? As I only fix some part of the frontend.

I mean the merge checks, frontend build is failing
image

**Review by David-DB88 — APPROVED** [review]

**Review by Mgrdich — APPROVED** [review]

**Comment by blacktower88** [comment]
Hi, I'm very sorry that I accidentally clicked the remove assignment icon, can you please assign to me again? I wanted to check something, but I hit the wrong button. It was a silly mistake and I apologize for any inconvenience.

**Comment by Haarolean** [comment]
> Hi, I'm very sorry that I accidentally clicked the remove assignment icon, can you please assign to me again? I wanted to check something, but I hit the wrong button. It was a silly mistake and I apologize for any inconvenience.

lol no worries

**Comment by Haarolean** [comment]
@blacktower88 ping me once you're done, we'll fix e2e tests

**Comment by blacktower88** [comment]
@Haarolean I am not sure but I think I finished. Frontend build and test was passed. Please let me know if there is anything to be corrected.

**Review by Haarolean — APPROVED** [review]
