### PR TITLE
BE: Make webclient use system proxy

### LINKED ISSUE #3868: Version Check Doesn't Use Proxy Settings
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

The version check fails and displays a 'null' version in the UI when the server is running in an environment that requires a proxy for internet access.

Attempts to configure proxy settings using HTTP_PROXY/HTTPS_PROXY environment variables or using http.proxyHost/https.proxyHost properties do not appear to work.

### Expected behavior

Proxy settings should be used in the WebClient that connects to github to obtain the version information and that should then be displayed in the UI

### Your installation details

App is deployed in a Kubernetes cluster running in AWS behind a web proxy for internet access.
App Version: 0.7 - fdd9ad9
Helm Chart Version: 0.7.0
Application config is sensitive and contains nothing but a broker URL.  These are the environment variables used to configure the proxy with fake setting values:

```
    - name: JAVA_OPTS
      value: "-Dhttp.proxyHost=http://example.com -Dhttp.proxyPort:8080 -Dhttps.proxyHost=http://example.com -Dhttps.proxyPort:8080"
    - name: HTTP_PROXY
      value: http://example.com:8080
    - name: HTTPS_PROXY
      value: http://example.com:8080
    - name: http_proxy
      value: http://example.com:8080
    - name: https_proxy
      value: http://example.com:8080
```

### Steps to reproduce

Configure as per above and navigate to the application.  Hover the cursor over the version check which displays a 'null' version value.  No errors in the logs.

### Screenshots

_No response_

### Logs

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Haarolean**
- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)
Make webclient use system proxy. Fixes #3868

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary)
- [ ] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by iliax — APPROVED** [review]

File: kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/GithubReleaseInfo.java [hunk 1]
```diff
@@ -31,7 +33,15 @@ public GithubReleaseInfo() {
...
-    this.refreshMono = WebClient.create()
+    var httpClient = HttpClient.create()
+        .proxyWithSystemProperties();
+
+    var webClient = WebClient
+        .builder()
+        .clientConnector(new ReactorClientHttpConnector(httpClient))
+        .build();
+
+    this.refreshMono = webClient
```
Comment (iliax) [inline kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/GithubReleaseInfo.java:44]: let use `new WebClientConfigurator().build()`  here
