### PR TITLE
BE: RBAC: Fix viewable topics filter

### LINKED ISSUE #3872: The 'all-topics' view does not display according to the RBAC filter
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

I was working with RBAC to filter permissions by topics, and the issue I'm facing is that in the "all-topics" URI, unlike with schemas or other tabs, it doesn't display the filtered topic unless I search for them in the search bar.

### Expected behavior

It should display, like in the rest of the tabs, only the topics that comply with the RBAC configuration.

### Your installation details

1 - 7.0 version
2 - Im not using it
3 - This is the RBAC that I'm using

resource: topic
        value: "dev.*"
        actions: all

### Steps to reproduce

Simply modify the configuration file in the topic permissions section to allow access only to specific topics.

### Screenshots

image
image

### Logs

_No response_

### Additional context

1 - I have tried all the methods listed in the documentation to define permissions on a topic

### PR DESCRIPTION
**Pull request by Haarolean**
- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)
Closes #3872 

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary)
- [ ] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: kafka-ui-api/src/test/java/com/provectus/kafka/ui/util/AccessControlServiceMock.java [hunk 1]
```diff
@@ -16,7 +17,7 @@ public AccessControlService getMock() {
     when(mock.validateAccess(any())).thenReturn(Mono.empty());
     when(mock.isSchemaAccessible(anyString(), anyString())).thenReturn(Mono.just(true));
 
-    when(mock.isTopicAccessible(any(), anyString())).thenReturn(Mono.just(true));
+    when(mock.filterViewableTopics(any(), anyString())).thenReturn(Mono.just(Collections.emptyList()));
```
Comment (iliax) [inline kafka-ui-api/src/test/java/com/provectus/kafka/ui/util/AccessControlServiceMock.java:20]: I think it should be `when(mock.filterViewableTopics(any(), any())).then(i -> Mono.just(i.getArgument(0)));`

**Review by iliax — APPROVED** [review]

File: kafka-ui-api/src/test/java/com/provectus/kafka/ui/util/AccessControlServiceMock.java (hunk 1 above)
Comment (Haarolean) [reply kafka-ui-api/src/test/java/com/provectus/kafka/ui/util/AccessControlServiceMock.java:20]: thanks, done
